### ISSUE TITLE
Server session initialization

### ISSUE THREAD

**Issue by tz70s** [dsngroup/broke#21]
I think server session collection is shared between multiple channels, concurrently. It can be initialized at `Server` when started, and pass it through args.
Also, is the map thread safe?

https://github.com/dsngroup/broke/blob/21a3ee85599081610267d4097fdff975ac057cb7/broke-broker/src/main/java/org/dsngroup/broke/broker/channel/handler/ProtocolProcessor.java#L37

**Comment by allenlee820202** [comment]
I am also considering to integrate server session collection, message pool and subscribe pool into the server context. And pass the server context to all the channels as the argument.

But whether to use a static class or singleton pattern is still a problem. For the integration using server context, I think all of these data pools should be instantiated so the singleton pattern should be used.

The server session collection should be a concurrent hash map. That's my fault. And also, maybe I'll rename it into server session pool for naming consistency.

**Comment by tz70s** [comment]
Sure, it's fine pass them in server context. I think it's better initialized them (session collection, message pool, subscribe pool) when `Server` or `ServerContext` is constructed. Not really need to use static or singleton actually, b.c. I think singleton pattern is used when you are a library maker.

**Comment by allenlee820202** [comment]
I see. I'll adjust it into a normal class initiation method and keep them in the server context.

**Comment by tz70s** [comment]
Once you've done it, reference this issue by adding #21 in commit.

**Comment by tz70s** [comment]
Close this.
