### ISSUE TITLE
Sync or not sync on protocol processor

### ISSUE THREAD

**Issue by tz70s** [dsngroup/broke#22]
At least it will not synchronized with static, you can use:
```java
synchronized(this)
// or
synchronized(ctx)
```
However, sync this to avoid race on unique `clientId` may not really needed? 

https://github.com/dsngroup/broke/blob/21a3ee85599081610267d4097fdff975ac057cb7/broke-broker/src/main/java/org/dsngroup/broke/broker/channel/handler/ProtocolProcessor.java#L42

**Comment by allenlee820202** [comment]
I synchronized this because: in case of 2 clients with the same clientId requesting for the session may cause race condition.

One optimization alternative is to synchronize the "getSession" function rather than synchronizing here.

**Comment by tz70s** [comment]
IMHO, use sync here is fine instead of sync in `getSession`, just sync with `session context` or `this` instead of static sync (`ProtocolProcessor.class`). But additional ask, so the `clientId` creation from message is not limited, do we need an additional information for client side to use the correct (available) id?

**Comment by allenlee820202** [comment]
OK, I'll narrow down the synchronization range to ```this```

By the MQTT specification, the client can set a zero length client ID, which will be considered as a special case. And the ```cleanSession``` flag should be set to true. The server will assign one for the client and accept the connection. Maybe I'll try to implement this mechanism.

**Comment by allenlee820202** [comment]
I found some problem in the MQTT specification about zero-length ```clientId```

In case of the client sets a zero-length ```clientId```, there's no way the client can get its server-assigned ```clientId``` (Because the ```CONNACK``` message doesn't contain the ```clientId```). That means a reconnection from such client can never gets its old session back.

I think a well-designed randomly assignment of ```clientId``` on the client side can still avoid the duplication problem of ```clientId```.

**Comment by tz70s** [comment]
Yes, but the duplication problem may still need to be resolved by server side. To get a more significant progress, we can first ignore this, but leave this issue remain.

**Comment by tz70s** [comment]
BTW, the identity of session in HTTP (cookie), is assigned by server-side. Not sure if there's any reason that an `clientId` created by client-side. 
i.e. the workflow of retrieving an session.
```
1. client -> connect to server
2. server -> check is connect, server assigned an unique id for client which used for session recognition. Carry this in ack.
3. client kept this id for next operations (e.g. publish)
```

**Comment by allenlee820202** [comment]
I guess the MQTT protocol wants to minimize the message size of CONNACK. And unlike HTTP, MQTT assumes there's not so much clients. So the client id assignment at the client side may be more efficient.

**Comment by tz70s** [comment]
Take a look at [this](https://github.com/andsel/moquette/blob/master/broker/src/main/java/io/moquette/spi/impl/ProtocolProcessor.java#L228) implementation. 

1. Client side generate `clientId`
2. If the clientId is not generate, then server side generate a random one.
3. If it is conflict, abort it.

But I still think this is not efficient, lol.
