### ISSUE TITLE
Usage of message pool

### ISSUE THREAD

**Issue by allenlee820202** [dsngroup/broke#32]
I want to make sure the right usage of message pool.
In my first thought, the message pool is used to store all publish messages from the publishers. If a new subscriber subscribes a topic which matches one of the topics in the message pool, the matched messages can be publish to this new subscriber. Let's call it message replay mechanism.
The message replay mechanism can also be extended to a group of subscribers. If there are multiple subscribers with new subscriptions which belongs to the same consumer group, the matched messages can be dispatched to this consumer group based on the dispatch algorithm.
@tz70s Is this right?

**Comment by tz70s** [comment]
Actually, it's not really **storing** them, you can flush out after dispatching. The important thing is the **recognition structure** for dispatching algorithm.
Keep contents remain can have additional mechanisms as you mentioned, but it is not really important currently.

**Comment by allenlee820202** [comment]
I'm not sure the message pool is necessary for the dispatch algorithm. Currently, publishing to subscribers is handled by the **publisher's message handler** on the server. It performs the dispatch algorithm based on only a **single publish message** rather than a bunch of messages.

In my thought, if the publish message is stored to the message pool first. I think there will be a **dedicated thread** that performs dispatch algorithm based on this message pool. All the message handlers is only responsible for placing the received publish messages into the message pool and leave the dispatch job to this thread.
